### ISSUE TITLE
fix(bridge): `TypeError: Cannot create property 'gasLimit' on string '0x9e2445'`

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.EthBridge#39]
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot create property 'gasLimit' on string '0x9e2445'
    at Method.outputBlockFormatter [as outputFormatter] (/app/node_modules/web3-core-helpers/lib/formatters.js:255:20)
    at Method.formatOutput (/app/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/app/node_modules/web3-core-method/lib/index.js:523:33)
    at /app/node_modules/web3-core-requestmanager/lib/index.js:308:9
    at /app/node_modules/@trufflesuite/web3-provider-engine/index.js:240:9
    at /app/node_modules/async/internal/once.js:12:16
    at replenish (/app/node_modules/async/internal/eachOfLimit.js:61:25)
    at /app/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/app/node_modules/async/eachLimit.js:43:36)
    at /app/node_modules/async/internal/doLimit.js:9:16
    at end (/app/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at WebsocketSubprovider._handleSocketMessage (/app/node_modules/@trufflesuite/web3-provider-engine/subproviders/websocket.js:123:5)
    at WebSocket.onMessage (/app/node_modules/@trufflesuite/web3-provider-engine/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/app/node_modules/@trufflesuite/web3-provider-engine/node_modules/ws/lib/websocket.js:720:20)
```

**Comment by riemannulus** [comment]
This problem is caused by multiple `Web3` objects sharing one `HDWalletProvider` object . `HDWallertProvider` requires a unique string ID for each request, and it occurs when the ID that `Web3` generates each sequentially overlaps the ID used inside the `HDWalletProvider`.

**Comment by riemannulus** [comment]
So, continue to the upper conversation, we need to change the `Web3` object to have each `Provider` object.

**Comment by JaiveerYadav** [comment]
check the url that use in hdwalletProvider for connect with infura i.e use https instend of wss.
