### ISSUE TITLE
fix(bridge): `Error: invalid signature length`

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.EthBridge#62]
See also https://github.com/odanado/aws-kms-provider/issues/281

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: invalid signature length
    at Object.recover (/app/node_modules/aws-kms-provider/dist/crypto.js:33:15)
    at /app/node_modules/aws-kms-provider/dist/signature.js:38:40
    at Array.filter (<anonymous>)
    at Function.fromDigest (/app/node_modules/aws-kms-provider/dist/signature.js:37:52)
    at KmsSigner.sign (/app/node_modules/aws-kms-provider/dist/signer/kms-signer.js:17:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async KmsProvider.signTransaction (/app/node_modules/aws-kms-provider/dist/provider.js:65:27)
```

**Comment by moreal** [comment]
Watch https://github.com/odanado/aws-kms-provider/pull/283 pull request
