### ISSUE TITLE
fix(bridge): `Error: PollingBlockTracker - encountered an error while attempting to update latest block`

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.EthBridge#63]
```
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined
    at PollingBlockTracker._performSync (/app/node_modules/eth-block-tracker/src/polling.js:51:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by moreal** [comment]
Ref https://github.com/trufflesuite/truffle/issues/3357

**Comment by moreal** [comment]
# 🤔 The problem

***Why this error kills the bridge application?***

# 📔 Research Note

The function `PollingBlockTracker._performSync:51` lines are below:

```javascript
      try {
        await this._updateLatestBlock()
        await timeout(this._pollingInterval, !this._keepEventLoopActive)
      } catch (err) {
        const newErr = new Error(`PollingBlockTracker - encountered an error while attempting to update latest block:\n${err.stack}`)
        try {
          this.emit('error', newErr)
        } catch (emitErr) {
          console.error(newErr)
        }
        await timeout(this._retryTimeout, !this._keepEventLoopActive)
      }
```

Because the error message shows only its stack without its message, we can't know the reason perfectly 😞 
The actual estimated error flow is like below:

1. `bridge.main` creates `KmsProvider` instance.
1. `KmsProvider` create `Web3ProviderEngine` (i.e. `private KmsProvider.engine`) instance.
1. `KmsProvider` calls `Web3ProviderEngine.start`.
    ```js
        this.engine.start();
    ```
1. `Web3ProviderEngine.start` register the new event listener and the registration calls `PollingBlockTracker.start` through `BaseBlockTracker._onNewListener`, `BaseBlockTracker._maybeStart`.
1. Then the `PollingBlockTracker` starts to get the latest block number periodically. See also [the source file](https://github.com/MetaMask/eth-block-tracker/blob/main/src/PollingBlockTracker.ts).
1. If it failed to get the latest block number, it fails and emits an `error` event through itself. Because the `BaseBlockTracker` inherits `SafeEventEmitter` and `SafeEventEmitter` inherits `EventEmitter`.

The process is the above I described step by step.
So, when the `EventEmitter` emits `error` and it kills the program because the error hasn't been handled.

I prepared the test code to see `EventEmitter.emit('error')` kills the program.

```js
import EventEmitter from "events";

class A extends EventEmitter {
    constructor() {
        super()
    }

    f(): void {
        this.emit("error")
    }
}

async function main() {
    const a = new A();
    setInterval(() => {
        a.f();
    }, 1000);
}

main().then(() => {
    console.log("Done")
}).catch(error => {
    console.log("Error")
    console.error(error);
    process.exit(-1);
})
```

When you run the above code, you will see like below:

```
Done
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (undefined)
    at new NodeError (node:internal/errors:363:5)
    at A.emit (node:events:354:17)
    at A.emit (node:domain:470:12)
    at A.f (PATH\planetarium\NineChronicles.EthBridge\bridge\test.ts:10:14)
    at Timeout._onTimeout (PATH\planetarium\NineChronicles.EthBridge\bridge\test.ts:18:11)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

Because the error hasn't been unhandled, the program seems dead.

# 💊 Solution

Maybe, the solution is to register an error handler through `process.on(uncaughtException, ...)`. In the above test code, I added the line to register the handler and I could see:

```
Done
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (undefined)
    at new NodeError (node:internal/errors:363:5)
    at A.emit (node:events:354:17)
    at A.emit (node:domain:470:12)
    at A.f (C:\Users\dogeo\github\planetarium\NineChronicles.EthBridge\bridge\test.ts:10:14)
    at Timeout._onTimeout (C:\Users\dogeo\github\planetarium\NineChronicles.EthBridge\bridge\test.ts:18:11)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ERR_UNHANDLED_ERROR',
  context: undefined
} uncaughtException
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (undefined)
    at new NodeError (node:internal/errors:363:5)
    at A.emit (node:events:354:17)
    at A.emit (node:domain:470:12)
    at A.f (C:\Users\dogeo\github\planetarium\NineChronicles.EthBridge\bridge\test.ts:10:14)
    at Timeout._onTimeout (C:\Users\dogeo\github\planetarium\NineChronicles.EthBridge\bridge\test.ts:18:11)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ERR_UNHANDLED_ERROR',
  context: undefined
} uncaughtException
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (undefined)
    at new NodeError (node:internal/errors:363:5)
    at A.emit (node:events:354:17)
    at A.emit (node:domain:470:12)
    at A.f (C:\Users\dogeo\github\planetarium\NineChronicles.EthBridge\bridge\test.ts:10:14)
    at Timeout._onTimeout (C:\Users\dogeo\github\planetarium\NineChronicles.EthBridge\bridge\test.ts:18:11)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ERR_UNHANDLED_ERROR',
  context: undefined
} uncaughtException
<... REPEAT>
```

# ➕ P.S.

The reason to fail to get the latest block number in `PollingBlockTracker` seems Infura availability problem.
I looked up the logs from Sentry events, and I can see the Infura returns 504 Gateway timeout error and failed (i.e. the program was dead).
 
![image](https://user-images.githubusercontent.com/26626194/134668441-5127ca55-31be-4987-abfe-2ae04f740a0a.png)
